version: "3.8"

services:

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    networks:
      - database
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html

  database:
    image: mariadb:11.2
    env_file:
      - .env
    networks:
      - database
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

#  frontend:
#    ports:
#      - "80:80"

  myadmin:
    image: phpmyadmin:latest
    environment:
      PMA_ARBITRARY: 1
    networks:
      - database
    ports:
      - "8000:80"

networks:
  database:

volumes:
  db_data:
